Streamed micAssess
scipion-em/scipion-em-cryoassess pull request #7
Opened 2021-03-24 12:12 UTC by DaniDelHoyo

Streamed version of the micAssess protocol. 
The structure of the output directories is maintained, temporal output directories are generated in 'tmp' for each pass and results are moved to the final output in 'extra'.

2021-03-24 12:14 UTC, DaniDelHoyo commented
I have also noticed that the cryoAssess software does not correctly downsample the inputs in micassess.py .
I have raised an issue in their github ( https://github.com/cianfrocco-lab/Automatic-cryoEM-preprocessing/issues/15 )

2021-03-24 12:33 UTC, cossorzano commented
While they fix their code, we may consider doing the downsampling ourselves. What do you think?

2021-03-24 16:02 UTC, DaniDelHoyo commented
What do you mean with doing it ourselves? Adding code in scipion which does it? 
My suggestion is just modifiying their code in local, because it is a 1 line change and their code creates, uses and removes the input in one step, so we could not downsample it from the outside.

2021-03-24 21:42 UTC, azazellochg requested changes

2021-03-24 21:42 UTC, azazellochg commented on cryoassess/protocols/protocol_micassess.py
> +        form.addSection("Streaming")
Please use self._defineStreamingParams(form) instead

2021-03-24 21:42 UTC, azazellochg commented on cryoassess/protocols/protocol_micassess.py
> +      sameTxt = 'data_\n\nloop_\n_rlnMicrographName \n'
Please use Table class from emtable.

2021-03-24 21:46 UTC, azazellochg commented
Also, the protocol test fails.

2021-03-25 01:19 UTC, DaniDelHoyo commented on cryoassess/protocols/protocol_micassess.py
> +        form.addSection("Streaming")
Hi Grigory, the current code is a copy of the _defineStreamingParams. I did not use it directly because like that I don't know if it is possible to change the default values of the parameters, specially the batch size which by default is 1. I didn't like the idea of working in batches of 1 and I think the default value should be higher. Is there a way to change it while calling the method? Or should we expect from the user to change it? I think the default values should be something reasonable from the begining

2021-03-25 01:23 UTC, DaniDelHoyo commented on cryoassess/protocols/protocol_micassess.py
> +      sameTxt = 'data_\n\nloop_\n_rlnMicrographName \n'
In this method I am writing what would be the "header" of these star files which will be latter extended with the micrographs names. If I use a Table and I write it when it is empty, the key of the column (rlnMicrographName) is not written, so I decided to write it directly. I get it would not be the more elegant way, but that is how I made it work. Could you suggest me how to make it better using Table?

2021-03-25 01:26 UTC, DaniDelHoyo commented
The test passes for me, could you please send the details of the error to check what is happening?

2021-03-25 13:28 UTC, DaniDelHoyo commented on cryoassess/protocols/protocol_micassess.py
> +        form.addSection("Streaming")
I found how to redefine the defaults, and now the function _defineStreamingParams is used as requested

2021-03-25 14:21 UTC, azazellochg commented on cryoassess/protocols/protocol_micassess.py
> +      sameTxt = 'data_\n\nloop_\n_rlnMicrographName \n'
Ah, understood.

2021-03-25 14:34 UTC, azazellochg commented
Hm, on another machine the test works.

2021-03-25 14:40 UTC, azazellochg approved these changes

2021-03-25 14:40 UTC, merged